@echo off

REM
REM   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
REM   ;;;                                                                  ;;;
REM   ;;;  Dynamic Link Binaries-Setup Packages                            ;;;
REM   ;;;  Property of AMD-ID.com, do not distribute without crediting     ;;;
REM   ;;;  or mentioning owners                                            ;;;
REM   ;;;  RdN_ID-Community/drivers/distribution                           ;;;
REM   ;;;                                                                  ;;;
REM   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
REM

CLS&COLOR 0E
START /b %NIRCMD% mediaplay 2500 "%SNDASK%"
SET MNPSEL=MiniPort Standard Mode&SET PARAMASK=MANAPARAM&SET ZCALSTYPE=ZCALSPROXYD_0000&GOTO ZCALSBEGIN

:ZCALSBEGIN
cls
GOTO %ZCALSTYPE%

:ZCALSATI_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSATI_0000found
if %ERRORLEVEL% EQU 1 GOTO ZCALSATI_0001
:ZCALSATI_0000found
set PROXYMODE=vn1
set WMINUM=0000
set ADAPNUM=0
call .\Bin64\ATIVaxyASIC.cmd

:ZCALSATI_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSATI_0001found
if %ERRORLEVEL% EQU 1 GOTO ZCALSATI_0002
:ZCALSATI_0001found
set PROXYMODE=vn1
set WMINUM=0001
set ADAPNUM=1
call .\Bin64\ATIVaxyASIC.cmd

:ZCALSATI_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSATI_0002found
if %ERRORLEVEL% EQU 1 GOTO ZCALSATI_0003
:ZCALSATI_0002found
set PROXYMODE=vn1
set WMINUM=0002
set ADAPNUM=2
call .\Bin64\ATIVaxyASIC.cmd

:ZCALSATI_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSATI_0003found
if %ERRORLEVEL% EQU 1 GOTO ZCALSDONE
:ZCALSATI_0003found
set PROXYMODE=vn1
set WMINUM=0003
set ADAPNUM=3
call .\Bin64\ATIVaxyASIC.cmd

:ZCALSPROXYA_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYA_0000found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYA_0001
:ZCALSPROXYA_0000found
set PROXYMODE=vn2
set WMINUM=0000
set ADAPNUM=0
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYA_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYA_0001found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYA_0002
:ZCALSPROXYA_0001found
set PROXYMODE=vn2
set WMINUM=0001
set ADAPNUM=1
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYA_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYA_0002found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYA_0003
:ZCALSPROXYA_0002found
set PROXYMODE=vn2
set WMINUM=0002
set ADAPNUM=2
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYA_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYA_0003found
if %ERRORLEVEL% EQU 1 GOTO ZCALSDONE
:ZCALSPROXYA_0003found
set PROXYMODE=vn2
set WMINUM=0003
set ADAPNUM=3
call .\Bin64\ATIVaxyGPUV.cmd
GOTO ZCALSDONE

:ZCALSPROXYB_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYB_0000found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYB_0001
:ZCALSPROXYB_0000found
set PROXYMODE=vn3
set WMINUM=0000
set ADAPNUM=0
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYB_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYB_0001found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYB_0002
:ZCALSPROXYB_0001found
set PROXYMODE=vn3
set WMINUM=0001
set ADAPNUM=1
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYB_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYB_0002found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYB_0003
:ZCALSPROXYB_0002found
set PROXYMODE=vn3
set WMINUM=0002
set ADAPNUM=2
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYB_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYB_0003found
if %ERRORLEVEL% EQU 1 GOTO ZCALSDONE
:ZCALSPROXYB_0003found
set PROXYMODE=vn3
set WMINUM=0003
set ADAPNUM=3
call .\Bin64\ATIVaxyGPUV.cmd
GOTO ZCALSDONE

:ZCALSPROXYC_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYC_0000found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYC_0001
:ZCALSPROXYC_0000found
set PROXYMODE=vn4
set WMINUM=0000
set ADAPNUM=0
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYC_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYC_0001found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYC_0002
:ZCALSPROXYC_0001found
set PROXYMODE=vn4
set WMINUM=0001
set ADAPNUM=1
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYC_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYC_0002found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYC_0003
:ZCALSPROXYC_0002found
set PROXYMODE=vn4
set WMINUM=0002
set ADAPNUM=2
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYC_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYC_0003found
if %ERRORLEVEL% EQU 1 GOTO ZCALSDONE
:ZCALSPROXYC_0003found
set PROXYMODE=vn4
set WMINUM=0003
set ADAPNUM=3
call .\Bin64\ATIVaxyGPUV.cmd
GOTO ZCALSDONE

:ZCALSPROXYD_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYD_0000found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYD_0001
:ZCALSPROXYD_0000found
set PROXYMODE=vn5
set WMINUM=0000
set ADAPNUM=0
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYD_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYD_0001found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYD_0002
:ZCALSPROXYD_0001found
set PROXYMODE=vn5
set WMINUM=0001
set ADAPNUM=1
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYD_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYD_0002found
if %ERRORLEVEL% EQU 1 GOTO ZCALSPROXYD_0003
:ZCALSPROXYD_0002found
set PROXYMODE=vn5
set WMINUM=0002
set ADAPNUM=2
call .\Bin64\ATIVaxyGPUV.cmd

:ZCALSPROXYD_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO ZCALSPROXYD_0003found
if %ERRORLEVEL% EQU 1 GOTO ZCALSDONE
:ZCALSPROXYD_0003found
set PROXYMODE=vn5
set WMINUM=0003
set ADAPNUM=3
call .\Bin64\ATIVaxyGPUV.cmd
GOTO ZCALSDONE

:ZCALSDONE
cls
GOTO %PARAMASK%

:MANAPARAM
CLS
COLOR 0E
START /b %NIRCMD% mediaplay 2500 "%SNDASK%"
SET TWKSEL=AMD Default Parameter&GOTO FactoryAMD_0000

:FactoryAMD_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryAMD_0000found
if %ERRORLEVEL% EQU 1 GOTO FactoryAMD_0001
:FactoryAMD_0000found
cls
set WMINUM=0000
call .\Bin64\ATILibASIC.cmd
cls

:FactoryAMD_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryAMD_0001found
if %ERRORLEVEL% EQU 1 GOTO FactoryAMD_0002
:FactoryAMD_0001found
cls
set WMINUM=0001
call .\Bin64\ATILibASIC.cmd
cls

:FactoryAMD_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryAMD_0002found
if %ERRORLEVEL% EQU 1 GOTO FactoryAMD_0003
:FactoryAMD_0002found
cls
set WMINUM=0002
call .\Bin64\ATILibASIC.cmd
cls

:FactoryAMD_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryAMD_0003found
if %ERRORLEVEL% EQU 1 GOTO FactoryAMDCompleted
:FactoryAMD_0003found
cls
set WMINUM=0003
call .\Bin64\ATILibASIC.cmd
cls

:FactoryAMDCompleted
GOTO MNPORTDONE

:FactoryRdNID_0000
%CENUMQUERY% %ENUM_0000% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryRdNID_0000found
if %ERRORLEVEL% EQU 1 GOTO FactoryRdNID_0001
:FactoryRdNID_0000found
cls
set WMINUM=0000
call .\Bin64\ATILibGPUV.cmd
cls

:FactoryRdNID_0001
%CENUMQUERY% %ENUM_0001% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryRdNID_0001found
if %ERRORLEVEL% EQU 1 GOTO FactoryRdNID_0002
:FactoryRdNID_0001found
cls
set WMINUM=0001
call .\Bin64\ATILibGPUV.cmd
cls

:FactoryRdNID_0002
%CENUMQUERY% %ENUM_0002% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryRdNID_0002found
if %ERRORLEVEL% EQU 1 GOTO FactoryRdNID_0003
:FactoryRdNID_0002found
cls
set WMINUM=0002
call .\Bin64\ATILibGPUV.cmd
cls

:FactoryRdNID_0003
%CENUMQUERY% %ENUM_0003% /v %RADVWMIC% > nul
if %ERRORLEVEL% EQU 0 GOTO FactoryRdNID_0003found
if %ERRORLEVEL% EQU 1 GOTO FactoryRdNIDCompleted
:FactoryRdNID_0003found
cls
set WMINUM=0003
call .\Bin64\ATILibGPUV.cmd
cls

:FactoryRdNIDCompleted
:MNPORTDONE
CLS
COLOR 0F
ECHO  ============================================================================================================
ECHO.
ECHO   COMPLETED: %MNPSEL%
ECHO              %TWKSEL%
ECHO          ### REQURIED SYSTEM REBOOT
ECHO.
ECHO  ============================================================================================================
START /b %NIRCMD% mediaplay 2500 "%SNDPOPUP%"
call %WINDIR%\SYSTEM32\PING.EXE -n 3 0.0.0.0 > nul